### ISSUE TITLE
python bindings progress

### ISSUE THREAD

**Issue by pythonmobile** [simonhf/sharedhashfile#2]
It seems that there was interest for this project to provide python bindings. any progress on that front? (I'd vote for using cffi to do this).

Also: Does this project support hash tables without using mmap. Pure named shared memory implementation? I don't need persistence, but would be nice to have write locks on particular key, value pairs.

**Comment by hexerei** [comment]
python bindings are moving to interest here as well now :)

**Comment by EliFinkelshteyn** [comment]
Was there ever anything committed on this front? I'd be really interested in Python bindings and potentially willing to help write some code to get them finished.

**Comment by simonhf** [comment]
Hmmm... the Python bindings stalled. Maybe it's time to un-stall them again :-)

**Comment by simonhf** [comment]
Closing this issue because I don not think the Python bindings are going to happen :-( Can open it again if they ever do :-)
