### ISSUE TITLE
Key value pairs

### ISSUE THREAD

**Issue by Globik** [simonhf/sharedhashfile#4]
Is it possible to store value as a struct ? Like in glib ghashtable does?

**Comment by simonhf** [comment]
@Globik I'm not familiar with glib ghashtable. Do you have a small and working example of storing a value as a struct using glib ghashtable? If so, I'll take a look at it. Thanks!

**Comment by Globik** [comment]
Yes, @simonhf , I have one simple example with GHashTable "container".
I am wondering about different implementations of hashes. Frankly to say the memory shared hashes are a new theme and it's just like Jesus Christ after dying.

Especially a C struct with function pointers
https://github.com/Globik/kore-mediasoup/blob/master/training/hash/ghash/m.c
I'm qustioning there are normally hash tables for simple data? Like strings and integers? Boolean?

**Comment by simonhf** [comment]
We can re-open this issue once there's a working example I can try out... closing for now.
