### ISSUE TITLE
How to query entries in this database from php?

### ISSUE THREAD

**Issue by jobs-git** [simonhf/sharedhashfile#6]
As the title says, how to query information in this database from php?

How do we do:

SELECT ID FROM table where col2=asdf;

or

SELECT * FROM table 2 left join table1 1 where col2=asdf;

**Comment by jobs-git** [comment]
I see, how do we do the following in C++?

SELECT ID FROM table where col2=asdf;

or

SELECT * FROM table 2 left join table1 1 where col2=asdf;

**Comment by simonhf** [comment]
That's an interesting question.

Short answer is that there is no C++ or API or query language to do want you want. Longer answer is that you could develop similar functionality to what you want using special features of the existing API:

Although the database is of the 'NoSQL' variety which means key,values and no query language, there is a rare NoSQL feature whereby when a key is stored then a Unique ID / UID (sometimes called a 'stable hint' in academic papers on hash tables) is returned, therefore allowing the key to be accessed in the future via the original key, or the UID. This feature could be used to implement the functionality you desire.

For example, if you added the key 'asdf' then the UID('asdf') could be prepended to a bunch of other keys and the resulting UIDs could be appended to the 'asdf' key value. In this way, the key 'asdf' would end up with a list of all keys prepended with the UID('asdf'). In this way you could build arbitrary data structures using the UID feature, including the one desired. Interestingly the UID does not take up any extra storage or metadata in the database, and it also doesn't change even if the memory locations of the underlying key,value data changes, e.g. as the database expands.

**Comment by jobs-git** [comment]
Were could I probably get any documentation about sharedhashfile APIs?

**Comment by simonhf** [comment]
You can look at the header files and look at the test source code too for usage. Also, compared to other key value stores then SharedHashFile is tiny and just a couple of 1,000 LOC, e.g. something like Cassandra is more like 1 million LOC.

**Comment by windrunner414** [comment]
@jobs-git A example: [https://github.com/windrunner414/swoole-src/tree/sharedhashfile](https://github.com/windrunner414/swoole-src/tree/sharedhashfile)

map.php
`
<?php
$map = new swoole_map('/dev/shm', 'test');
$map->set('key', 'hello world');
var_dump($map->get('key'));
`
