### ISSUE TITLE
shf_put_key_val

### ISSUE THREAD

**Issue by pakipaki2000** [simonhf/sharedhashfile#9]
Hi,

shf_put_key_val, can we insert by "key", without knowing the uuid? And also, how to get the uuid from a Key? Please post just a few examples.

Would be really helpful! Thanks so much

**Comment by simonhf** [comment]
Hi @pakipaki2000 ,

Thanks for the questions. I'll try and answer below. Feel free to ask more questions.

"shf_put_key_val, can we insert by "key", without knowing the uuid?" Yes, it's the only way to insert a key. You can only insert a key using the key itself, but once it's inserted, you can access the key via the key itself (which would be the regular and expected way in any other hash table), or via the UID discovered when originally inserting the key.

This is also why the 'put' operation only exists in the 'key' variant as the shf_put_key_val() [1] function, whereas the 'get', 'upd', and 'del' operations all exist with 'key' and 'uid' variants, e.g. shf_del_key_val() deletes the key,value pair via the key, and shf_del_uid_val() deletes the key,value pair via the UID.

FYI this line [2] in one of the test files shows such a key being inserted and the result of shf_put_key_val() is the UID.

"how to get the uuid from a Key" In the current version of the code then the UID is only returned upon key insertion. However, there is an update coming soon which allows the UID to be returned later too, e.g. let's say the key was inserted in the past and the caller didn't record the UID, the update coming soon will allow the caller to find the original key and get the UID again.

Hope this answers your questions!

[1] https://github.com/simonhf/sharedhashfile/blob/7c8716a0be8c585d9dd64c263f440fd517f64308/src/shf.h#L366
[2] https://github.com/simonhf/sharedhashfile/blob/7c8716a0be8c585d9dd64c263f440fd517f64308/src/test.9.shf.c#L73

**Comment by pakipaki2000** [comment]
Thank you! 
i'll watch your github for the update

**Comment by pakipaki2000** [comment]
PS: 
What is the "3" in your example?

**Comment by simonhf** [comment]
Good question!
The '3' is the number of value bytes to read from the value pointer. In the example the value pointer points to "val" which is a zero terminated string. So you might think that the number of bytes is not necessary because SHF could continue along the value string until it hits the zero termination. While this is true, it only works for non-binary values which can have a zero termination. Whereas SHF supports binary values, and the 3 bytes of the value could be all zeros if the caller wanted. So that's why the number of bytes for the value length must be given.

**Comment by pakipaki2000** [comment]
I see! Thanks so much.
Have a great day ahead.

**Comment by simonhf** [comment]
> there is an update coming soon which allows the UID to be returned later

@pakipaki2000 The update is submitted now. Most key,value access functions now set the thread local variable shf_uid. Here's [1] an example in the tests where shf_get_key_val() sets shf_uid.

[1] https://github.com/simonhf/sharedhashfile/blob/6464d96b72be6e5422ea7ba50d03311dbfea9145/src/test.9.shf.c#L135

**Comment by pakipaki2000** [comment]
Amazing!  Thank you so much.
